### ISSUE TITLE
Seems to be an issue with nonces.

### ISSUE THREAD

**Issue by larssn** [apkoponen/wp-rest-api-oauth2#1]
The problem I'm seeing is pretty hard to pin down, as it seems to sporadically work, but happens when trying to access a protected WooCommerce resource (WC is now integrated with the core REST functionality of WP). You are simply denied access.

All of the following tests can be tried with the tool "Postman".
1. Do all the needed setup - add a oAuth2 client etc. No WC setup needed other than activating it.
2. Apply a minor hotfix to wp-rest-api-ouath2: `add_action( 'init', array( 'OA2_Server', 'init_autheticator' ) );` should be `add_action( 'plugins_loaded', array( 'OA2_Server', 'init_autheticator' ) );` (the init hook runs too late, and shouldn't be used to add other actions/filters)
3. Get an access token from your excellent plugin using the normal flow. This flow sets a number of WP cookies.
4. Request the resource `https://localhost/wp-json/wc/v1/orders`.

Sometimes this flow works: You get an empty array back (meaning zero orders, but you are allowed access).
Sometimes you are told that you don't have permission, and this is where my current debugging adventure is happening. On our multisite production environment it doesn't work at all for whatever reason.

A quick "fix" for this problem is deleting the wordpress_\* cookies in Postman; you are then allowed access (I haven't figured out yet why this works).

The "plugins_loaded" fix above, seems to have fixed the problem on my localhost, for the most part. This however doesn't seem to cut it for our production server.

I've found the exact line I need to comment out in WP (for our prod server to work), and its related to nonces:

```
wp-includes/rest-api.php:584

if ( null === $nonce ) {
// No nonce at all, so act as if it's an unauthenticated request.
//wp_set_current_user( 0 );
return true;
}
```

If wp_set_current_user is commented out, it all works. So the problem seem related to nonces. (I'm obviously looking for a real fix, without having to break core functionality.)

The reason the it normally breaks is because the user gets set to 0, and then WC checks if user 0 has permissions to see orders, which it hasn't.

Thoughts are welcomed; spent a while on this problem so far.

**Comment by larssn** [comment]
I found and fixed the issue. I'll close this and make a pull request shortly.

**Comment by apkoponen** [comment]
Hi,

The reason you're seeing the problems (and why commenting out wp-includes/rest-api.php:584 helps) is that cookie authentication works with WP-API only when you send nonces with the requests (more information http://v2.wp-api.org/guide/authentication/#cookie-authentication).

Do you need to use OAuth 2.0 tokens when the user is already logged-in or was this just a debuggin case?

A-P

**Comment by larssn** [comment]
Gonna close this again, think we discussed it fully in #2.

Feel free to reopen if you disagree.
