### ISSUE TITLE
Plugin activation causes no access to backend

### ISSUE THREAD

**Issue by gjeromeb** [apkoponen/wp-rest-api-oauth2#3]
Hi there,

I am experimenting with writing an App for my wordpress site, and thought this looked like a good way to add user authentication.

However, whenever I activate the plugin in the wordpress backend admin area, it then redirects me to the frontend (still logged in) and I can no longer access the backend. Am I doing something wrong?

Would appreciate your help, many thanks.

**Comment by apkoponen** [comment]
Hi,

interesting. Haven't seen that behaviour myself. A few questions to rule out common issues:
- What WordPress version are you running?
- Have you tried disabling all other plugins and switching to one of the default themse in order to rule out some sort of plugin/theme conflict?

A-P

**Comment by gjeromeb** [comment]
First of all thanks for the super quick reply :)

That was a good tip, I have isolated the issue to the following plugin, which seems to be causing a conflict:
https://en-gb.wordpress.org/plugins/remove-dashboard-access-for-non-admins/

Maybe you could take a look what is causing the conflict?

**Comment by apkoponen** [comment]
I pushed a commit that fixes the issue. Thanks for the bug report!

**Comment by gjeromeb** [comment]
Thank you for the super quick fix. I will try it out later :)
