### ISSUE TITLE
... oauth2/v1/logout idea.

### ISSUE THREAD

**Issue by larssn** [apkoponen/wp-rest-api-oauth2#5]
So we're in a situation where the client should be able to effectively logout, making the server remove the tokens tied to the user in question. (Again, this is in the context of a web app.)

My idea is an endpoint like in the subject. Client has his bearer token attached like normal, but after visiting that endpoint, the token(s) wont be valid anymore.

Or can you think of a better way to handle orphaned tokens? Waiting for the refresh token to expire would take a while. :)

**Comment by apkoponen** [comment]
Token revocation has been specified in the IETF [RFC 7009](https://tools.ietf.org/html/rfc7009). Unfortunately I don't have the time to implement it right now and I don't think you'd need such a rigid version.

You should be able to implement the functionality you're after yourself quite easily with something like the code below (untested). It removes all the tokens from the given user_id

```
<?php

function app_register_routes() {
	// Registers the revoke endpoint
	register_rest_route( 'app-oauth2', '/revoke', array(
		'methods'  => 'POST',
		'callback' => 'app_revoke_tokens',
	) );
}

add_action( 'rest_api_init', 'app_register_routes' );

function app_revoke_tokens( WP_REST_Request $request ) {
	$user_id     = intval( $request->get_param( 'user_id' ) );
	if(empty($user_id) || $user_id !== get_current_user_id()) {
		return new WP_Error("You don't have the right to do this!");
	}
	$args = array(
		'post_type' => array('oauth2_access_token', 'oauth2_refresh_token'),
		'post_status' => 'any',
		'author' => $user_id
	);
	$query = new WP_query( $args );
	$deleted_posts = array();
	foreach( $query->posts as $post ) {
		$result = wp_delete_post( $post->ID, true );
		if ( $result !== false ) {
			$deleted_posts[] = $result;
		}
	}
	return $deleted_posts;
}
```

Just to clarify, what was the original reason why you weren't using the default WordPress sessions for authenticating your requests? There you'd have login/logout without too much effort. If I understood corretly the app was written using Ionic so it should work pretty much out of the box?

**Comment by larssn** [comment]
Was a long time ago, but I believe the decision was made so we wouldn't have to store usernames/passwords in what is basically a javascript app. If the device gets stolen, the crooks would have the app info, but would still need to know the login info in WP to get anywhere.

Also I think the idea was: OAuth 2 is probably more future proof than a normal login.


Your plugin also allows us to theoretically make the user login via facebook/g+.

The flow would be:
User uses facebook's oauth2 flow, gets assigned an access token which is forwarded to our server. We lookup the access token on facebook, and check if we have a user that matches those records. If so: create an oauth2 token via your plugin which the user then uses to communicate with our platform.

That should be secure: We control the WP users, and their permissions, and no FB login would be able to bypass that.

EDIT
Thanks for the solution btw.
